apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 50000
      targetPort: 50000
      protocol: TCP
      name: slave
  selector:
    app: jenkins
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: jenkins-slave
#   labels:
#     app: jenkins
# spec:
#   ports:
#     - port: 5000
#       targetPort: 5000
#       protocol: TCP
#       name: tcp-5000
#   selector:
#     app: jenkins